function test_laplacian_nd()
%TEST_LAPLACIAN_ND Compare LAPLACIAN_ND with LAPLACIAN and test N-D cases.
%
%   TEST_LAPLACIAN_ND executes the 7,075 legacy 1D-3D reference cases.
%   Every output from LAPLACIAN_ND is compared with LAPLACIAN and with the
%   recorded JSON values.  It then checks 4D and 5D LAPLACIAN_ND problems
%   using the defining eigenpair equation and orthonormality.  The suite
%   also executes the documented examples and covers every public input
%   parsing and validation branch.
%
%   Run this test from MATLAB or Octave after adding this directory to the
%   path.  It requires laplacian_reference.json, generated by
%   GENERATE_LAPLACIAN_REFERENCE.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   License:  MIT / Apache-2.0
%   Copyright (c) 2026 A.V. Knyazev, Andrew.Knyazev@ucdenver.edu
%   $Revision: 1.0 $  $Date: 1-November-2026
%   Tested in GNU Octave Version: 11.3.0 and
%   MATLAB 26.2 (R2026b)
testDirectory = fileparts(mfilename('fullpath'));
fixturePath = fullfile(testDirectory, 'laplacian_reference.json');
assert(exist(fixturePath, 'file') == 2, ...
    'Missing reference fixture. Run generate_laplacian_reference first.');
fixture = jsondecode(fileread(fixturePath));
assert(fixture.schemaVersion == 1 && fixture.caseCount == 7075, ...
    'Unexpected Laplacian reference fixture.');

tolerance = 1e-12;
test_documented_examples(tolerance);
test_input_handling(tolerance);
for caseIndex = 1:fixture.caseCount
    reference = fixture.cases(caseIndex);
    N = double(reference.N(:).');
    B = normalize_boundary_conditions(reference.B);
    M = double(reference.M);
    order = prod(N);

    evalc('[legacyA, legacyLambda, legacyV] = laplacian(N, B, M);');
    evalc('[newA, newLambda, newV] = laplacian_nd(N, B, M);');
    expectedA = reshape(double(reference.A), order, order);
    expectedLambda = reshape(double(reference.lambda), M, 1);
    expectedV = reshape(double(reference.V), order, M);
    caseLabel = sprintf('N=%s, B={%s}, M=%d', ...
        mat2str(N), strjoin(B, ', '), M);

    assert_close(full(legacyA), expectedA, tolerance, 'legacy A', caseLabel);
    assert_close(legacyLambda, expectedLambda, tolerance, ...
        'legacy lambda', caseLabel);
    assert_close(legacyV, expectedV, tolerance, 'legacy V', caseLabel);
    assert(issparse(newA), 'New A is not sparse for %s.', caseLabel);
    assert_close(full(newA), full(legacyA), tolerance, 'new A', caseLabel);
    assert_close(newLambda, legacyLambda, tolerance, 'new lambda', caseLabel);
    assert_close(newV, legacyV, tolerance, 'new V', caseLabel);
end

test_extended_dimensions(tolerance);
fprintf(['Laplacian N-D test suite: 3 documented examples, input validation, ', ...
    '%d parity cases, and 2 N-D cases passed.\n'], fixture.caseCount);
end

function test_documented_examples(tolerance)
[A, lambda, V] = laplacian_nd(3, 2);
expectedA = [2, -1, 0; -1, 2, -1; 0, -1, 2];
expectedLambda = [2 - sqrt(2); 2];
assert(issparse(A), 'The 1D example must return a sparse matrix.');
assert_close(full(A), expectedA, tolerance, '1D example A', 'N=3, M=2');
assert_close(lambda, expectedLambda, tolerance, '1D example lambda', ...
    'N=3, M=2');
assert_eigenpairs(A, lambda, V, tolerance, '1D documented example');

N = [3, 2];
B = {'DN', 'P'};
evalc('[A, lambda, V] = laplacian_nd(N, B, 2);');
evalc('[legacyA, legacyLambda, legacyV] = laplacian(N, B, 2);');
assert_close(full(A), full(legacyA), tolerance, '2D example A', 'N=[3 2]');
assert_close(lambda, legacyLambda, tolerance, '2D example lambda', ...
    'N=[3 2]');
assert_close(V, legacyV, tolerance, '2D example V', 'N=[3 2]');
assert_eigenpairs(A, lambda, V, tolerance, '2D documented example');

N = [2, 2, 2, 2];
B = {'DD', 'NN', 'P', 'DN'};
evalc('[A, lambda, V] = laplacian_nd(N, B, 2);');
assert(isequal(size(A), [16, 16]), 'The N-D example A size is incorrect.');
assert(isequal(size(lambda), [2, 1]), ...
    'The N-D example lambda size is incorrect.');
assert(isequal(size(V), [16, 2]), 'The N-D example V size is incorrect.');
assert_eigenpairs(A, lambda, V, tolerance, 'N-D documented example');
end

function test_input_handling(tolerance)
% Valid input forms and the M == 0 output branch.
[defaultA, defaultLambda, defaultV] = laplacian_nd([2, 3]);
[explicitA, explicitLambda, explicitV] = laplacian_nd([2, 3], ...
    {'DD', 'DD'});
assert(issparse(defaultA), 'Default input must return sparse A.');
assert(isempty(defaultLambda) && isempty(defaultV), ...
    'Default input must use M = 0.');
assert_close(full(defaultA), full(explicitA), tolerance, ...
    'default-boundary A', 'N=[2 3]');
assert(isempty(explicitLambda) && isempty(explicitV), ...
    'Boundary-only input must use M = 0.');

[numericA, numericLambda] = laplacian_nd([2, 3], 1);
[boundaryA, boundaryLambda] = laplacian_nd([2, 3], {'DD', 'DD'}, 1);
assert_close(full(numericA), full(boundaryA), tolerance, ...
    'numeric-second-input A', 'N=[2 3], M=1');
assert_close(numericLambda, boundaryLambda, tolerance, ...
    'numeric-second-input lambda', 'N=[2 3], M=1');

[zeroA, zeroLambda, zeroV] = laplacian_nd(2, {'NN'}, 0);
assert(issparse(zeroA) && isempty(zeroLambda) && isempty(zeroV), ...
    'M = 0 must return sparse A and empty eigenpair outputs.');

% Noninteger N rounds once and reports its documented warning.
lastwarn('');
evalc('[roundedA, roundedLambda] = laplacian_nd([1.2, 2.8], 1);');
[~, warningIdentifier] = lastwarn;
assert(strcmp(warningIdentifier, ...
    'BLOPEX:laplacian_nd:NonIntegerGridSize'), ...
    'Noninteger N must issue the documented warning.');
[integerA, integerLambda] = laplacian_nd([1, 3], 1);
assert_close(full(roundedA), full(integerA), tolerance, ...
    'rounded-grid A', 'N=[1.2 2.8]');
assert_close(roundedLambda, integerLambda, tolerance, ...
    'rounded-grid lambda', 'N=[1.2 2.8]');

expect_error(@() laplacian_nd(), 'BLOPEX:laplacian_nd:NoInputArguments');
expect_error(@() laplacian_nd(1, {'DD'}, 1, 0), ...
    'BLOPEX:laplacian_nd:TooManyInputs');
expect_error(@request_four_outputs, ...
    {'BLOPEX:laplacian_nd:TooManyOutputs', 'Octave:invalid-fun-call'});

expect_error(@() laplacian_nd('2'), ...
    'BLOPEX:laplacian_nd:WrongVectorOfGridPoints');
expect_error(@() laplacian_nd([1; 2]), ...
    'BLOPEX:laplacian_nd:WrongVectorOfGridPoints');
expect_error(@() laplacian_nd([1, 2; 3, 4]), ...
    'BLOPEX:laplacian_nd:WrongVectorOfGridPoints');
expect_error(@() laplacian_nd([]), ...
    'BLOPEX:laplacian_nd:WrongVectorOfGridPoints');
expect_error(@() laplacian_nd([NaN, 2]), ...
    'BLOPEX:laplacian_nd:WrongVectorOfGridPoints');
expect_error(@() laplacian_nd([Inf, 2]), ...
    'BLOPEX:laplacian_nd:WrongVectorOfGridPoints');
expect_error(@() laplacian_nd([1 + 1i, 2]), ...
    'BLOPEX:laplacian_nd:WrongVectorOfGridPoints');
expect_error(@() laplacian_nd([0, 2]), ...
    'BLOPEX:laplacian_nd:NonPositiveGridSize');
expect_error(@() laplacian_nd([-1, 2]), ...
    'BLOPEX:laplacian_nd:NonPositiveGridSize');

expect_error(@() laplacian_nd(2, 'DD'), ...
    'BLOPEX:laplacian_nd:InvalidSecondInput');
expect_error(@() laplacian_nd(2, [1, 2]), ...
    'BLOPEX:laplacian_nd:InvalidSecondInput');
expect_error(@() laplacian_nd(2, 'DD', 1), ...
    'BLOPEX:laplacian_nd:InvalidBdryConds');
expect_error(@() laplacian_nd([2, 2], {'DD'; 'NN'}, 1), ...
    'BLOPEX:laplacian_nd:InvalidBdryConds');
expect_error(@() laplacian_nd(2, {1}, 1), ...
    'BLOPEX:laplacian_nd:InvalidBdryConds');
expect_error(@() laplacian_nd(2, {'DX'}, 1), ...
    'BLOPEX:laplacian_nd:InvalidBdryConds');

expect_error(@() laplacian_nd(2, {'DD'}, '1'), ...
    'BLOPEX:laplacian_nd:WrongNumberOfEigenvalues');
expect_error(@() laplacian_nd(2, {'DD'}, [1, 2]), ...
    'BLOPEX:laplacian_nd:WrongNumberOfEigenvalues');
expect_error(@() laplacian_nd(2, {'DD'}, 1.5), ...
    'BLOPEX:laplacian_nd:InvalidNumberOfEigs');
expect_error(@() laplacian_nd(2, {'DD'}, -1), ...
    'BLOPEX:laplacian_nd:InvalidNumberOfEigs');
expect_error(@() laplacian_nd(2, {'DD'}, 3), ...
    'BLOPEX:laplacian_nd:InvalidNumberOfEigs');
expect_error(@() laplacian_nd(2, {'DD'}, NaN), ...
    'BLOPEX:laplacian_nd:WrongNumberOfEigenvalues');
expect_error(@() laplacian_nd(2, {'DD'}, Inf), ...
    'BLOPEX:laplacian_nd:WrongNumberOfEigenvalues');
expect_error(@() laplacian_nd(2, {'DD'}, 1 + 1i), ...
    'BLOPEX:laplacian_nd:WrongNumberOfEigenvalues');
end

function test_extended_dimensions(tolerance)
test_case([3, 2, 2, 2], {'DD', 'DN', 'NN', 'P'}, 2, tolerance);
test_case([2, 2, 2, 2, 2], {'P', 'ND', 'DD', 'NN', 'DN'}, 2, tolerance);
end

function test_case(N, B, M, tolerance)
evalc('[A, lambda, V] = laplacian_nd(N, B, M);');
order = prod(N);
assert(issparse(A), 'A must be sparse for N=%s.', mat2str(N));
assert(isequal(size(A), [order, order]), 'A has the wrong size.');
assert(isequal(size(lambda), [M, 1]), 'lambda has the wrong size.');
assert(isequal(size(V), [order, M]), 'V has the wrong size.');
assert_eigenpairs(A, lambda, V, tolerance, sprintf('N=%s', mat2str(N)));
end

function assert_eigenpairs(A, lambda, V, tolerance, caseLabel)
assert(norm(A - A.', 'fro') <= tolerance, 'A is not symmetric for %s.', ...
    caseLabel);
assert(norm(V.' * V - eye(size(V, 2)), 'fro') <= tolerance, ...
    'V is not orthonormal for %s.', caseLabel);
assert(norm(A * V - V * diag(lambda), 'fro') <= tolerance, ...
    'A, lambda, and V do not satisfy the eigenpair equation for %s.', ...
    caseLabel);
assert(all(diff(lambda) >= -tolerance), 'lambda is not sorted for %s.', ...
    caseLabel);
end

function B = normalize_boundary_conditions(value)
if iscell(value)
    B = value(:).';
elseif ischar(value)
    B = cellstr(value);
else
    error('BLOPEX:laplacian_nd:InvalidFixtureBoundaryConditions', ...
        'Fixture boundary conditions must be strings.');
end
end

function assert_close(actual, expected, tolerance, valueName, caseLabel)
assert(isequal(size(actual), size(expected)), ...
    '%s has the wrong size for %s.', valueName, caseLabel);
assert(max(abs(actual(:) - expected(:))) <= tolerance, ...
    '%s differs for %s.', valueName, caseLabel);
end

function request_four_outputs()
[~, ~, ~, ~] = laplacian_nd(1);
end

function expect_error(functionHandle, expectedIdentifiers)
if ischar(expectedIdentifiers)
    expectedIdentifiers = {expectedIdentifiers};
end
try
    functionHandle();
catch exception
    assert(any(strcmp(exception.identifier, expectedIdentifiers)), ...
        'Expected %s, received %s.', strjoin(expectedIdentifiers, ' or '), ...
        exception.identifier);
    return
end
error('BLOPEX:laplacian_nd:ExpectedErrorNotRaised', ...
    'Expected error %s was not raised.', strjoin(expectedIdentifiers, ' or '));
end